### PR TITLE
Adding child count information to message ResourceInfo

### PR DESCRIPTION
**Pull request by DeepDiver1975**
I'd like to propose an additional optional field for the ResourceInfo message:  child_count

With respect to human facing frontends (like phoenix) it could be valuable information to show the number of contained elements.

Let me know what you think of this. THX

### CODE REVIEW

**Comment by labkode** [comment]
@DeepDiver1975 thanks, it makes sense. 

I just wander if we should introduce some recursive fields like these ones:
https://blog.widodh.nl/2015/04/playing-with-cephfs-recursive-statistics/

Which one could be interested for Phoenix? And also with the child_count did you expect it to be recursive or only for the direct children (1st level)?

**Comment by DeepDiver1975** [comment]
> And also with the child_count did you expect it to be recursive or only for the direct children (1st level)?

Since I know the implications on computing such values I was only thinking about the direct children.

I guess it would be reasonable to add both? Or even split up these values:

- number of files
- number of folders
- number of symlinks
- number of ....
- total number of children

But this might already be much ....

**Comment by labkode** [comment]
@DeepDiver1975 I think it could be doable at least enterprise-grade storage like Ceph and EOS support them out of the box :)

**Comment by DeepDiver1975** [comment]
so we better define a stuct holding all these folder stats?

**Pull request closed without merging**
