### PR TITLE
Share expiration

### PR DESCRIPTION
**Pull request by C0rby**
Added changes to the API to support expiration on user and group shares.

### CODE REVIEW

**Review by labkode — APPROVED** [review]

**Comment by labkode** [comment]
@C0rby PR is good we just need to run the CI in the new infra, @micbar can you enable the cs3apis as well to run in ownCloud's drone?

**Comment by micbar** [comment]
@labkode @C0rby Done. But there is an issue, the pipeline needs a gh token to publish the generated code.

@vascoguita How should we proceed?

**Comment by vascoguita** [comment]
> @labkode @C0rby Done. But there is an issue, the pipeline needs a public key to publish the generated code.
> 
> @vascoguita How should we proceed?

I'm looking into it.
Ideally, there would be no SSH key at all, specially in a PR-triggered workflow.
Anyone could get the private key by making a PR with `echo $SSH_KEY` in the .drone.yml file.

I'll try to migrate this workflow to GH actions this afternoon. If there is urgency, I could temporarily @micbar the ssh key for the ownCloud drone instance.

**Comment by micbar** [comment]
@vascoguita Thank you for the quick reaction. Afternoon sounds good 😄

**Pull request merged**
