### PR TITLE
ocm: Add user to GenerateInviteTokenRequest

### PR DESCRIPTION
**Pull request by ishank011**

### CODE REVIEW

**Comment by labkode** [comment]
@ishank011 the token is sent to a mail, not to an user_id. If we knew the user_id we wouldn't have developed the Invitation Flow ;)

**Comment by ishank011** [comment]
@labkode We aren't taking this from the user. The GenerateInviteToken method creates a random token and returns that to the user, which the user can mail to users from other providers.
The workflow is: GET /invite -> GenerateInviteToken -> InviteManager. The manager needs to know with which user the token has to be associated with.

**Comment by labkode** [comment]
@ishank011 clear now :)

**Comment by labkode** [comment]
> @labkode This user_id is to store which user created the token. The GenerateInviteToken method creates a random token and returns that to the user, which the user can mail to users from other providers. The workflow is: GET /invite -> GenerateInviteToken -> InviteManager. The manager needs to know with which user the token has to be associated with.

The user when generating the token will be already logged in to the system, the InviteManager will know what user is asking to generate the token. 
My question is: why you need to expose the user_id into this message? For what I understand only the token will be consumed by higher layers to send the mail.

**Comment by ishank011** [comment]
Yes that is correct. What I was previously thinking is in the HTTP service, we'll get the user from the context and then pass that to the gateway GRPC, but instead we can use the context at the invite manager level only. Thanks!

**Pull request closed without merging**
