### PR TITLE
cs3: added Preferences API.

### PR DESCRIPTION
**Pull request by Mohitty**

### CODE REVIEW

**Comment by labkode** [comment]
Hi, please use for the SetKeyRequest the following fields:

```
string key = 1;
string val = 2;
```

and for the GetKeyRequest:

```
string key = 1;
```

Keep the opaque fields, I want you  to start with something simple from the protocol buffer definition, to the implementation in the reva daemon, we'll add complexity later.

**Comment by labkode** [comment]
@Mohitty also, is a good practive to squash your commits into one in a PR so its easier to track the changes introduced by your PR, you can read about rebasing your changes in this guide: https://help.github.com/en/articles/about-pull-request-merges

**Comment by Mohitty** [comment]
> @Mohitty also, is a good practive to squash your commits into one in a PR so its easier to track the changes introduced by your PR, you can read about rebasing your changes in this guide: https://help.github.com/en/articles/about-pull-request-merges

Thanks! I will follow that from now on.

**Comment by labkode** [comment]
Update the comments on the definitions accordingly, they still point to provider info

**Pull request merged**
